[versions]
assertj = "3.24.2"
jcpi = "1.4.1"
junit = "5.9.2"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
jcpi = { module = "com.fluxchess.jcpi:jcpi", version.ref = "jcpi" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
